# Copyright lowRISC Contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ["self-hosted", "nixos"]

    defaults:
      run:
        shell: "nix develop -c bash -e {0}"

    steps:
      - uses: actions/checkout@v5

      - name: Prepare Nix environment
        run: |
          true

      - name: License check
        run: |
          reuse lint

      - name: Generate software buildsystem
        run: |
          cmake -B build -S .

      - name: Lint - Clang Format
        run: |
          ./clang-format.sh check

      - name: Build software
        run: |
          cmake --build build -j $(nproc)

      - name: Nix build
        run: |
          nix build
